### PR TITLE
TCP state machine diagram and description

### PR DESCRIPTION
**Pull request by guybedford**
I've written up my own understanding of the TCP state machine so far as I've best been able to interpret it for implementation.

This provides a formal definition of all states and intermediate states, along with the pollable state in each of these.

This is what I'm going ahead with in the JCO implementation. If there are any inaccuracies I would be very grateful to know.

### CODE REVIEW

**Comment by guybedford** [comment]
Rendered version in https://github.com/WebAssembly/wasi-sockets/blob/3a9f9c4d311785960360c08d2824b051029a41e1/README.md#tcp-state-machine.

**Comment by guybedford** [comment]
Note also in this interpretation I've specified access denied as always recoverable based on reverting into the previous state before the start call.

**Comment by badeend** [comment]
Awesome, this helps a lot!

This looks about 90% right to me. Some remarks:
- "finishBind() error" goes from TCP_BIND_READY to TCP_ERROR. This doesn't seem correct. Binds can be retried.
- You've modeled `TCP_ERROR` and `TCP_CLOSED` as two dinstinct end-states. Why is that?
- An error from `startListen` reverts back to `TCP_BOUND`, but a (non-`would-block`) error from `finishListen` terminates in `TCP_ERROR`. In general, there shouldn't any discrepencies in which state `start-*` errors and `finish-*` error end up. Because in preview3+ this distinction won't exist anymore. Which is why I changed this (very recently)
 in https://github.com/WebAssembly/wasi-sockets/pull/92
- You reference the terms "granted" and "denied" a lot, but I don't see how permissions are relevant to the state machine. I think these terms could be generalized to Success and Failure, where `access-denied` is just _one_ of the error codes.

I'm not so sure about codifying the separation between:
- `TCP_BIND` & `TCP_BIND_READY`
- `TCP_CONNECT` & `TCP_CONNECT_READY`
- `TCP_LISTEN` & `TCP_LISTEN_READY`
I can understand that JCO decided to implement it this way, but the distinction between these two shouldn't be observable from the consumer's POV, right? In my mind, they're more a concern of the pollable's implementation, rather than the socket state.


> The TCP_CONNECT_READY and TCP_LISTEN_READY states should eagerly handle socket connection and socket listen calls respectively, so that the finish calls represent completion of the asynchronous operation. Implementations may perform blocking connect and listen in the connectFinish and listenFinish calls, but this is discouraged.

I don't understand what you mean with this. Implementations may definitely _not_ block on `connect` and POSIX `listen` never blocks.

---

I've updated the diagram and documentation over here: https://github.com/badeend/wasi-sockets/commit/beef70ff5f46871893441c3a4c9b217a9d70a089. Changes:
- updated the terminology to match the existing proposal.
- incorporated my remarks from above
- decoupled the socket states from the pollable logic.
- integrated the state definitions into the WITs themselves.
- added some clarifications from #89 into the WITs
- these changes got quite bulky, so I moved it into its own file.

**Comment by guybedford** [comment]
Thanks I actually just pushed an update in https://github.com/WebAssembly/wasi-sockets/pull/95/commits/2f39db48273a6c92b18172bf6f12720fa2fdcf5a that corrects the first remark bullet point of yours, which I also just noticed this morning.

The update corrects the `_READY` state handling as you mention, but the reason I modelled these states was specifically to be able to have a model of the poll state machine that can directly map to the TCP state machine. With the one describable exception then only being when in the `LISTENING` state that the pollable corresponds to the socket IO, but in all other states the poll state is simply a binary decision function based on the socket state - IF we add the `_READY` states.

Because the pollables was my biggest point of misunderstanding and confusion (costing me a week in implementation time), this was my primary goal to ensure these states were fully described comprehensively and without any ambiguity.

> I don't understand what you mean with this. Implementations may definitely not block on connect and POSIX listen never blocks.

We initially implemented the `bind` and `listen` calls in the `bindFinish` and `listenFinish` methods. I was attempting to clarify that while this is possible, it is not the design. Again, trying to clarify a confusion we had that cost us development time.

Your changes look great otherwise - I do think adding the `_READY` states for the polls would be preferable though, and have submitted a PR to your change in https://github.com/badeend/wasi-sockets/pull/1.

Lastly, I also implemented the permission denied errors as recoverable, in that one could imagine later granting the permission on the system and then trying the operation again on the socket. I'm open to whatever here, but I think it would be good to specify this behaviour.

**Comment by guybedford** [comment]
After further review, the updates in https://github.com/badeend/wasi-sockets/commit/beef70ff5f46871893441c3a4c9b217a9d70a089 seem like they do cover everything here to me.

The only remaining clarification to still be answered that I have then is https://github.com/WebAssembly/wasi-sockets/issues/96.

**Comment by badeend** [comment]
> > Implementations may definitely not block on connect (...)

> We initially implemented the bind and listen calls in the bindFinish and listenFinish methods. I was attempting to clarify that while this is possible, it is not the design. Again, trying to clarify a confusion we had that cost us development time.

In POSIX, `bind` and `listen` never block, so calling them in the `finish-*` function is perfectly fine and even suggested in the readme. My remark about blocking was specifically on `connect`.

I've [appended notes](https://github.com/badeend/wasi-sockets/commit/b71a24ffd8e1e05440771d38fef08646051effb6) to my branch above to clarify this for future readers.

**Pull request closed without merging**
