### PR TITLE
WASI Preview2

### PR DESCRIPTION
**Pull request by badeend**
Update proposal to match the current WIT abilities, and also to match the design direction of WASI preview 2. Notable changes:

- Added `wasi-default-network`
- Replaced `resource`s with plain handle indexes along with manually defined `drop-....` functions
- Replaced `future<>` with `non-blocking/set-non-blocking/subscribe` functions
- Replaced `stream<>` with `wasi-io.input/output-stream` in the TCP module.
- Replaced `stream<>` with a custom `resolve-address-stream` in the name lookup module.
- Added `shutdown` back in into the TCP module.

---

TODO: error codes. Using proper full names.

### CODE REVIEW

**Comment by badeend** [comment]
@sunfishcode , during our discussion yesterday we discovered an issue where wasi-libc can't differentiate between multiple preopened `network` handles, because at the moment when the IP addresses are provided to the host, the socket would have already need to been created.

I think one way to work around this is to split up the API interfaces into three parts. Summary:

```rs
type tcp-socket = u32
type tcp-connection = u32
type tcp-listener = u32


interface wasi-tcp-create-socket {
    /// Does NOT require a network capability handle.
    /// At time of creation, the socket is not bound to any `network` yet.
    create-tcp-socket: func(address-family: ip-address-family) -> result<tcp-socket, error>
}

interface wasi-tcp {

    // # Socket configuration functions. 

    address-family: func(this: tcp-socket) -> ip-address-family
    local-address: func(this: tcp-socket) -> result<ip-socket-address, error>
    set-local-address: func(this: tcp-socket, value: ip-socket-address) -> result<_, error>
    remote-address: func(this: tcp-socket) -> result<ip-socket-address, error>
    set-remote-address: func(this: tcp-socket, value: ip-socket-address) -> result<_, error>
    keep-alive: func(this: tcp-socket) -> result<bool, error>
    set-keep-alive: func(this: tcp-socket, value: bool) -> result<_, error>
    no-delay: func(this: tcp-socket) -> result<bool, error>
    set-no-delay: func(this: tcp-socket, value: bool) -> result<_, error>
    receive-buffer-size: func(this: tcp-socket) -> result<u64, error>
    set-receive-buffer-size: func(this: tcp-socket, value: u64) -> result<_, error>
    send-buffer-size: func(this: tcp-socket) -> result<u64, error>
    set-send-buffer-size: func(this: tcp-socket, value: u64) -> result<_, error>
    unicast-hop-limit: func(this: tcp-socket) -> result<u8, error>
    set-unicast-hop-limit: func(this: tcp-socket, value: u8) -> result<_, error>
    ipv6-only: func(this: tcp-socket) -> result<bool, error>
    set-ipv6-only: func(this: tcp-socket, value: bool) -> result<_, error>
    set-backlog-size: func(this: tcp-socket, value: u64) -> result<_, error>
    non-blocking: func(this: tcp-socket) -> result<bool, error>
    set-non-blocking: func(this: tcp-socket, value: bool) -> result<_, error>
    subscribe: func(this: tcp-socket) -> pollable

    // # Connection functions.
    // Unlike `create-tcp-socket`, `connect` _does_ require a network handle.
    // On success, `this` socket is associated with the `network`, and can't be used as an argument to `connect` (or listen) again.
    connect: func(this: tcp-socket, network: network) -> result<tuple<tcp-connection, input-stream, output-stream>, error>
    shutdown: func(this: tcp-connection, shutdown-type: shutdown-type) -> result<_, error>

    // # Listener functions.
    // Unlike `create-tcp-socket`, `listen` _does_ require a network handle.
    // On success, `this` socket is associated with the `network`, and can't be used as an argument to `listen` (or connect) again.
    listen: func(this: tcp-socket, network: network) -> result<tcp-listener, error>
    accept: func(this: tcp-listener) -> result<tuple<tcp-connection, input-stream, output-stream>, error>

}
```

Example server:
```rs
let preOpenedNetwork = ...;
let sock = create-tcp-socket(ip-address-family::ipv4); // Does not require a network capability handle
sock.set-local-address("0.0.0.0:80"); // Does not make a `bind` syscall
sock.set-backlog-size(1024); // Optional. Will be passed in as an argument to the `listen` syscall.
let listener = sock.listen(preOpenedNetwork); // Will perform the actual bind&listen syscalls.
while (true) {
    let client = listener.accept();
}
```

Example client:
```rs
let preOpenedNetwork = ...;
let sock = create-tcp-socket(ip-address-family::ipv4); // Does not require a network capability handle
sock.set-remote-address("1.2.3.4:80"); // Does not make a `connect` syscall
sock.set-non-blocking(true);
let conn, i, o = sock.connect(preOpenedNetwork); // Performs the `connect` syscall. Also will be non-blocking in this example.
// ...
conn.shutdown();
```

**Comment by sunfishcode** [comment]
I think that makes sense. This makes creating a socket a link-time authority, but to actually bind/connect with anything, it requires a network handle at runtime, which feels practical.

**Comment by sunfishcode** [comment]
>     connect: func(this: tcp-socket, network: network) -> result<tuple<tcp-connection, input-stream, output-stream>, error>

Would this consume the `tcp-socket`, or is there a need for the `tcp-socket` to remain live in addition to the new `tcp-connection`?

**Comment by badeend** [comment]
I've just updated the PR. In this version `tcp-connection` does not exist, and Yes the tcp-socket remains alive.

<details>
  <summary>Updated examples</summary>
 
Server:
```rs
let sock = create-tcp-socket(ip-address-family::ipv6); // Does not require a network capability handle
sock.ipv6-only(true);
sock.set-listen-backlog-size(1024);
// ...

// `attach` is probably automatically called by libc in its `bind` implementation.
// At this point libc knows which address+port will be bound to and can use that
// information to select a suitable network handle.
sock.attach(preOpenedNetwork);
sock.bind("[::]:80");
sock.listen();
while (true) {
	let client = sock.accept();
}
```

Client:
```rs
let sock = create-tcp-socket(ip-address-family::ipv6); // Does not require a network capability handle
sock.set-non-blocking(true);
sock.set-keep-alive(true);
// ...

// `attach` is probably automatically called by libc in its `connect` implementation.
// At this point libc knows which address+port will be connected to and can use that
// information to select a suitable network handle.
sock.attach(preOpenedNetwork);
let (input, output) = sock.connect("[::1]:80"); // Will be non-blocking in this example.
// ...
sock.shutdown();
```

</details>

**Review by sunfishcode — APPROVED** [review]
This looks great to me! There will surely be things to iterate on, but this PR looks good.

**Comment by sunfishcode** [comment]
This looks to me like it's in good shape overall. What would you think of merging this now, to make it easier to iterate on from here?

**Pull request merged**
